package model;
// Generated 4 juil. 2016 00:52:55 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * Alerte generated by hbm2java
 */
public class Alerte implements java.io.Serializable {

	private String alertId;
	private Equipement equipement;
	private String alertDes;
	private Date alertDate;

	public Alerte() {
	}

	public Alerte(String alertId, Equipement equipement) {
		this.alertId = alertId;
		this.equipement = equipement;
	}

	public Alerte(String alertId, Equipement equipement, String alertDes, Date alertDate) {
		this.alertId = alertId;
		this.equipement = equipement;
		this.alertDes = alertDes;
		this.alertDate = alertDate;
	}

	public String getAlertId() {
		return this.alertId;
	}

	public void setAlertId(String alertId) {
		this.alertId = alertId;
	}

	public Equipement getEquipement() {
		return this.equipement;
	}

	public void setEquipement(Equipement equipement) {
		this.equipement = equipement;
	}

	public String getAlertDes() {
		return this.alertDes;
	}

	public void setAlertDes(String alertDes) {
		this.alertDes = alertDes;
	}

	public Date getAlertDate() {
		return this.alertDate;
	}

	public void setAlertDate(Date alertDate) {
		this.alertDate = alertDate;
	}

}
