package model;
// Generated 4 juil. 2016 00:52:55 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Contrat generated by hbm2java
 */
public class Contrat implements java.io.Serializable {

	private String contratId;
	private Equipe equipe;
	private Entreprise entreprise;
	private String contratPath;
	private Date contratDatecrea;
	private String contratEmpcrea;
	private BigDecimal contratMontant;
	private BigDecimal contratPenalite;
	private Date contratddebut;
	private String contratloides;
	private int contratduree;
	
	public BigDecimal getContratMontant() {
		return contratMontant;
	}

	public void setContratMontant(BigDecimal contratMontant) {
		this.contratMontant = contratMontant;
	}

	public BigDecimal getContratPenalite() {
		return contratPenalite;
	}

	public void setContratPenalite(BigDecimal contratPenalite) {
		this.contratPenalite = contratPenalite;
	}

	public Date getContratddebut() {
		return contratddebut;
	}

	public void setContratddebut(Date contratddebut) {
		this.contratddebut = contratddebut;
	}

	public String getContratloides() {
		return contratloides;
	}

	public void setContratloides(String contratloides) {
		this.contratloides = contratloides;
	}

	public int getContratduree() {
		return contratduree;
	}

	public void setContratduree(int contratduree) {
		this.contratduree = contratduree;
	}

	public Contrat() {
	}

	public Contrat(String contratId, Equipe equipe, Entreprise entreprise) {
		this.contratId = contratId;
		this.equipe = equipe;
		this.entreprise = entreprise;
	}

	public Contrat(String contratId, Equipe equipe, Entreprise entreprise, String contratPath, Date contratDatecrea,
			String contratEmpcrea) {
		this.contratId = contratId;
		this.equipe = equipe;
		this.entreprise = entreprise;
		this.contratPath = contratPath;
		this.contratDatecrea = contratDatecrea;
		this.contratEmpcrea = contratEmpcrea;
	}

	public String getContratId() {
		return this.contratId;
	}

	public void setContratId(String contratId) {
		this.contratId = contratId;
	}

	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	public Entreprise getEntreprise() {
		return this.entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
	}

	public String getContratPath() {
		return this.contratPath;
	}

	public void setContratPath(String contratPath) {
		this.contratPath = contratPath;
	}

	public Date getContratDatecrea() {
		return this.contratDatecrea;
	}

	public void setContratDatecrea(Date contratDatecrea) {
		this.contratDatecrea = contratDatecrea;
	}

	public String getContratEmpcrea() {
		return this.contratEmpcrea;
	}

	public void setContratEmpcrea(String contratEmpcrea) {
		this.contratEmpcrea = contratEmpcrea;
	}

}
