package model;
// Generated 4 juil. 2016 00:52:55 by Hibernate Tools 3.6.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private String empId;
	private String empCin;
	private String empNom;
	private String empPrenom;
	private Date empDatenaiss;
	private String empUsername;
	private String empPassword;
	private Set<Equipe> equipes = new HashSet<Equipe>(0);
	private Set<Droit> droits = new HashSet<Droit>(0);

	public Employee() {
	}

	public Employee(String empId) {
		this.empId = empId;
	}

	public Employee(String empId, String empCin, String empNom, String empPrenom, Date empDatenaiss, String empUsername,
			String empPassword, Set<Equipe> equipes, Set<Droit> droits) {
		this.empId = empId;
		this.empCin = empCin;
		this.empNom = empNom;
		this.empPrenom = empPrenom;
		this.empDatenaiss = empDatenaiss;
		this.empUsername = empUsername;
		this.empPassword = empPassword;
		this.equipes = equipes;
		this.droits = droits;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getEmpCin() {
		return this.empCin;
	}

	public void setEmpCin(String empCin) {
		this.empCin = empCin;
	}

	public String getEmpNom() {
		return this.empNom;
	}

	public void setEmpNom(String empNom) {
		this.empNom = empNom;
	}

	public String getEmpPrenom() {
		return this.empPrenom;
	}

	public void setEmpPrenom(String empPrenom) {
		this.empPrenom = empPrenom;
	}

	public Date getEmpDatenaiss() {
		return this.empDatenaiss;
	}

	public void setEmpDatenaiss(Date empDatenaiss) {
		this.empDatenaiss = empDatenaiss;
	}

	public String getEmpUsername() {
		return this.empUsername;
	}

	public void setEmpUsername(String empUsername) {
		this.empUsername = empUsername;
	}

	public String getEmpPassword() {
		return this.empPassword;
	}

	public void setEmpPassword(String empPassword) {
		this.empPassword = empPassword;
	}

	public Set<Equipe> getEquipes() {
		return this.equipes;
	}
	public List<Equipe> getListEquipes() {
		return new ArrayList<Equipe>(this.equipes);
	}
	
	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}

	public Set<Droit> getDroits() {
		return this.droits;
	}

	public void setDroits(Set<Droit> droits) {
		this.droits = droits;
	}

}
