package model;
// Generated 4 juil. 2016 00:52:55 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entreprise generated by hbm2java
 */
public class Entreprise implements java.io.Serializable {

	private String entrepriseId;
	private String entrepriseNom;
	private String entrepriseStatusj;
	private String entrepriseNomcontact;
	private String entrepriseNum;
	private String entrepriseAdr;
	private Date entrepriseDatecrea;
	private String entrepriseRegcom;
	private BigDecimal entrepriseCapital;
	private String entrepriseEmpcrea;
	private Set<Contrat> contrats = new HashSet<Contrat>(0);
	private Set<Equipement> equipements = new HashSet<Equipement>(0);

	public Entreprise() {
	}

	public Entreprise(String entrepriseId) {
		this.entrepriseId = entrepriseId;
	}

	public Entreprise(String entrepriseId, String entrepriseNom, String entrepriseStatusj, String entrepriseNomcontact,
			String entrepriseNum, String entrepriseAdr, Date entrepriseDatecrea, String entrepriseEmpcrea,
			Set<Contrat> contrats, Set<Equipement> equipements) {
		this.entrepriseId = entrepriseId;
		this.entrepriseNom = entrepriseNom;
		this.entrepriseStatusj = entrepriseStatusj;
		this.entrepriseNomcontact = entrepriseNomcontact;
		this.entrepriseNum = entrepriseNum;
		this.entrepriseAdr = entrepriseAdr;
		this.entrepriseDatecrea = entrepriseDatecrea;
		this.entrepriseEmpcrea = entrepriseEmpcrea;
		this.contrats = contrats;
		this.equipements = equipements;
	}
	
	public String getEntrepriseRegcom() {
		return entrepriseRegcom;
	}

	public void setEntrepriseRegcom(String entrepriseRegcom) {
		this.entrepriseRegcom = entrepriseRegcom;
	}

	public BigDecimal getEntrepriseCapital() {
		return entrepriseCapital;
	}

	public void setEntrepriseCapital(BigDecimal entrepriseCapital) {
		this.entrepriseCapital = entrepriseCapital;
	}


	public String getEntrepriseId() {
		return this.entrepriseId;
	}

	public void setEntrepriseId(String entrepriseId) {
		this.entrepriseId = entrepriseId;
	}

	public String getEntrepriseNom() {
		return this.entrepriseNom;
	}

	public void setEntrepriseNom(String entrepriseNom) {
		this.entrepriseNom = entrepriseNom;
	}

	public String getEntrepriseStatusj() {
		return this.entrepriseStatusj;
	}

	public void setEntrepriseStatusj(String entrepriseStatusj) {
		this.entrepriseStatusj = entrepriseStatusj;
	}

	public String getEntrepriseNomcontact() {
		return this.entrepriseNomcontact;
	}

	public void setEntrepriseNomcontact(String entrepriseNomcontact) {
		this.entrepriseNomcontact = entrepriseNomcontact;
	}

	public String getEntrepriseNum() {
		return this.entrepriseNum;
	}

	public void setEntrepriseNum(String entrepriseNum) {
		this.entrepriseNum = entrepriseNum;
	}

	public String getEntrepriseAdr() {
		return this.entrepriseAdr;
	}

	public void setEntrepriseAdr(String entrepriseAdr) {
		this.entrepriseAdr = entrepriseAdr;
	}

	public Date getEntrepriseDatecrea() {
		return this.entrepriseDatecrea;
	}

	public void setEntrepriseDatecrea(Date entrepriseDatecrea) {
		this.entrepriseDatecrea = entrepriseDatecrea;
	}

	public String getEntrepriseEmpcrea() {
		return this.entrepriseEmpcrea;
	}

	public void setEntrepriseEmpcrea(String entrepriseEmpcrea) {
		this.entrepriseEmpcrea = entrepriseEmpcrea;
	}

	public Set<Contrat> getContrats() {
		return this.contrats;
	}

	public void setContrats(Set<Contrat> contrats) {
		this.contrats = contrats;
	}

	public Set<Equipement> getEquipements() {
		return this.equipements;
	}

	public void setEquipements(Set<Equipement> equipements) {
		this.equipements = equipements;
	}

}
