package model;
// Generated 4 juil. 2016 00:52:55 by Hibernate Tools 3.6.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Equipe generated by hbm2java
 */
public class Equipe implements java.io.Serializable {

	private String equipeId;
	private String equipeNom;
	private Date equipeDatecrea;
	private String equipeEmpcrea;
	private Set<Contrat> contrats = new HashSet<Contrat>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Equipe() {
	}

	public Equipe(String equipeId) {
		this.equipeId = equipeId;
	}

	public Equipe(String equipeId, String equipeNom, Date equipeDatecrea, String equipeEmpcrea, Set<Contrat> contrats,
			Set<Employee> employees) {
		this.equipeId = equipeId;
		this.equipeNom = equipeNom;
		this.equipeDatecrea = equipeDatecrea;
		this.equipeEmpcrea = equipeEmpcrea;
		this.contrats = contrats;
		this.employees = employees;
	}

	public String getEquipeId() {
		return this.equipeId;
	}

	public void setEquipeId(String equipeId) {
		this.equipeId = equipeId;
	}

	public String getEquipeNom() {
		return this.equipeNom;
	}

	public void setEquipeNom(String equipeNom) {
		this.equipeNom = equipeNom;
	}

	public Date getEquipeDatecrea() {
		return this.equipeDatecrea;
	}

	public void setEquipeDatecrea(Date equipeDatecrea) {
		this.equipeDatecrea = equipeDatecrea;
	}

	public String getEquipeEmpcrea() {
		return this.equipeEmpcrea;
	}

	
	public void setEquipeEmpcrea(String equipeEmpcrea) {
		this.equipeEmpcrea = equipeEmpcrea;
	}

	public Set<Contrat> getContrats() {
		return this.contrats;
	}

	public void setContrats(Set<Contrat> contrats) {
		this.contrats = contrats;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}
	
	
	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
