package model;
// Generated 4 juil. 2016 00:52:55 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipement generated by hbm2java
 */
public class Equipement implements java.io.Serializable {

	private String equipementId;
	private Entreprise entreprise;
	private String equipementNom;
	private String equipementIp;
	private String equipementUser;
	private String equipementPass;
	private Date equipementDatecrea;
	private String equipementEmpcrea;
	private Set<Alerte> alertes = new HashSet<Alerte>(0);
	private Set<Etatserveur> etatserveurs = new HashSet<Etatserveur>(0);

	public Equipement() {
	}

	public Equipement(String equipementId, Entreprise entreprise) {
		this.equipementId = equipementId;
		this.entreprise = entreprise;
	}

	public Equipement(String equipementId, Entreprise entreprise, String equipementNom, String equipementIp,
			String equipementUser, String equipementPass, Date equipementDatecrea, String equipementEmpcrea,
			Set<Alerte> alertes, Set<Etatserveur> etatserveurs) {
		this.equipementId = equipementId;
		this.entreprise = entreprise;
		this.equipementNom = equipementNom;
		this.equipementIp = equipementIp;
		this.equipementUser = equipementUser;
		this.equipementPass = equipementPass;
		this.equipementDatecrea = equipementDatecrea;
		this.equipementEmpcrea = equipementEmpcrea;
		this.alertes = alertes;
		this.etatserveurs = etatserveurs;
	}

	public String getEquipementId() {
		return this.equipementId;
	}

	public void setEquipementId(String equipementId) {
		this.equipementId = equipementId;
	}

	public Entreprise getEntreprise() {
		return this.entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
	}

	public String getEquipementNom() {
		return this.equipementNom;
	}

	public void setEquipementNom(String equipementNom) {
		this.equipementNom = equipementNom;
	}

	public String getEquipementIp() {
		return this.equipementIp;
	}

	public void setEquipementIp(String equipementIp) {
		this.equipementIp = equipementIp;
	}

	public String getEquipementUser() {
		return this.equipementUser;
	}

	public void setEquipementUser(String equipementUser) {
		this.equipementUser = equipementUser;
	}

	public String getEquipementPass() {
		return this.equipementPass;
	}

	public void setEquipementPass(String equipementPass) {
		this.equipementPass = equipementPass;
	}

	public Date getEquipementDatecrea() {
		return this.equipementDatecrea;
	}

	public void setEquipementDatecrea(Date equipementDatecrea) {
		this.equipementDatecrea = equipementDatecrea;
	}

	public String getEquipementEmpcrea() {
		return this.equipementEmpcrea;
	}

	public void setEquipementEmpcrea(String equipementEmpcrea) {
		this.equipementEmpcrea = equipementEmpcrea;
	}

	public Set<Alerte> getAlertes() {
		return this.alertes;
	}

	public void setAlertes(Set<Alerte> alertes) {
		this.alertes = alertes;
	}

	public Set<Etatserveur> getEtatserveurs() {
		return this.etatserveurs;
	}

	public void setEtatserveurs(Set<Etatserveur> etatserveurs) {
		this.etatserveurs = etatserveurs;
	}

}
