package model;
// Generated 4 juil. 2016 00:52:55 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;

/**
 * Etatserveur generated by hbm2java
 */
public class Etatserveur implements java.io.Serializable {

	private String etatId;
	private Equipement equipement;
	private BigDecimal etatCpu;
	private BigDecimal etatMem;
	private BigDecimal etatIf1In;
	private BigDecimal etatIf2In;
	private BigDecimal etatIf3In;
	private BigDecimal etatIf4In;
	private BigDecimal etatIf1Out;
	private BigDecimal etatIf2Out;
	private BigDecimal etatIf3Out;
	private BigDecimal etatIf4Out;

	public Etatserveur() {
	}

	public Etatserveur(String etatId, Equipement equipement) {
		this.etatId = etatId;
		this.equipement = equipement;
	}

	public Etatserveur(String etatId, Equipement equipement, BigDecimal etatCpu, BigDecimal etatMem,
			BigDecimal etatIf1In, BigDecimal etatIf2In, BigDecimal etatIf3In, BigDecimal etatIf4In,
			BigDecimal etatIf1Out, BigDecimal etatIf2Out, BigDecimal etatIf3Out, BigDecimal etatIf4Out) {
		this.etatId = etatId;
		this.equipement = equipement;
		this.etatCpu = etatCpu;
		this.etatMem = etatMem;
		this.etatIf1In = etatIf1In;
		this.etatIf2In = etatIf2In;
		this.etatIf3In = etatIf3In;
		this.etatIf4In = etatIf4In;
		this.etatIf1Out = etatIf1Out;
		this.etatIf2Out = etatIf2Out;
		this.etatIf3Out = etatIf3Out;
		this.etatIf4Out = etatIf4Out;
	}
	
	public String getIn() {
		return this.etatIf1In.add(this.etatIf2In.add(this.etatIf3In.add(this.etatIf4In))).toString() ;
	}
	public String getOut() {
		return this.etatIf1Out.add(this.etatIf2Out.add(this.etatIf3Out.add(this.etatIf4Out))).toString() ;
	}
	public String getEtatId() {
		return this.etatId;
	}

	public void setEtatId(String etatId) {
		this.etatId = etatId;
	}

	public Equipement getEquipement() {
		return this.equipement;
	}

	public void setEquipement(Equipement equipement) {
		this.equipement = equipement;
	}

	public BigDecimal getEtatCpu() {
		return this.etatCpu;
	}

	public void setEtatCpu(BigDecimal etatCpu) {
		this.etatCpu = etatCpu;
	}

	public BigDecimal getEtatMem() {
		return this.etatMem;
	}

	public void setEtatMem(BigDecimal etatMem) {
		this.etatMem = etatMem;
	}

	public BigDecimal getEtatIf1In() {
		return this.etatIf1In;
	}

	public void setEtatIf1In(BigDecimal etatIf1In) {
		this.etatIf1In = etatIf1In;
	}

	public BigDecimal getEtatIf2In() {
		return this.etatIf2In;
	}

	public void setEtatIf2In(BigDecimal etatIf2In) {
		this.etatIf2In = etatIf2In;
	}

	public BigDecimal getEtatIf3In() {
		return this.etatIf3In;
	}

	public void setEtatIf3In(BigDecimal etatIf3In) {
		this.etatIf3In = etatIf3In;
	}

	public BigDecimal getEtatIf4In() {
		return this.etatIf4In;
	}

	public void setEtatIf4In(BigDecimal etatIf4In) {
		this.etatIf4In = etatIf4In;
	}

	public BigDecimal getEtatIf1Out() {
		return this.etatIf1Out;
	}

	public void setEtatIf1Out(BigDecimal etatIf1Out) {
		this.etatIf1Out = etatIf1Out;
	}

	public BigDecimal getEtatIf2Out() {
		return this.etatIf2Out;
	}

	public void setEtatIf2Out(BigDecimal etatIf2Out) {
		this.etatIf2Out = etatIf2Out;
	}

	public BigDecimal getEtatIf3Out() {
		return this.etatIf3Out;
	}

	public void setEtatIf3Out(BigDecimal etatIf3Out) {
		this.etatIf3Out = etatIf3Out;
	}

	public BigDecimal getEtatIf4Out() {
		return this.etatIf4Out;
	}

	public void setEtatIf4Out(BigDecimal etatIf4Out) {
		this.etatIf4Out = etatIf4Out;
	}

}
