package model2;
// Generated 2 juin 2016 23:42:03 by Hibernate Tools 4.3.1.Final



/**
 * SfeCpuUsage generated by hbm2java
 */
public class SfeCpuUsage  implements java.io.Serializable {


     private SfeCpuUsageId id;

    public SfeCpuUsage() {
    }

    public SfeCpuUsage(SfeCpuUsageId id) {
       this.id = id;
    }
   
    public SfeCpuUsageId getId() {
        return this.id;
    }
    
    public void setId(SfeCpuUsageId id) {
        this.id = id;
    }




}


