package model2;
// Generated 2 juin 2016 23:42:03 by Hibernate Tools 4.3.1.Final



/**
 * SfeCpuUsageId generated by hbm2java
 */
public class SfeCpuUsageId  implements java.io.Serializable {


     private String scuServerId;
     private Short scuPerc;
     private String scuDate;

    public SfeCpuUsageId() {
    }

    public SfeCpuUsageId(String scuServerId, Short scuPerc, String scuDate) {
       this.scuServerId = scuServerId;
       this.scuPerc = scuPerc;
       this.scuDate = scuDate;
    }
   
    public String getScuServerId() {
        return this.scuServerId;
    }
    
    public void setScuServerId(String scuServerId) {
        this.scuServerId = scuServerId;
    }
    public Short getScuPerc() {
        return this.scuPerc;
    }
    
    public void setScuPerc(Short scuPerc) {
        this.scuPerc = scuPerc;
    }
    public String getScuDate() {
        return this.scuDate;
    }
    
    public void setScuDate(String scuDate) {
        this.scuDate = scuDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SfeCpuUsageId) ) return false;
		 SfeCpuUsageId castOther = ( SfeCpuUsageId ) other; 
         
		 return ( (this.getScuServerId()==castOther.getScuServerId()) || ( this.getScuServerId()!=null && castOther.getScuServerId()!=null && this.getScuServerId().equals(castOther.getScuServerId()) ) )
 && ( (this.getScuPerc()==castOther.getScuPerc()) || ( this.getScuPerc()!=null && castOther.getScuPerc()!=null && this.getScuPerc().equals(castOther.getScuPerc()) ) )
 && ( (this.getScuDate()==castOther.getScuDate()) || ( this.getScuDate()!=null && castOther.getScuDate()!=null && this.getScuDate().equals(castOther.getScuDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getScuServerId() == null ? 0 : this.getScuServerId().hashCode() );
         result = 37 * result + ( getScuPerc() == null ? 0 : this.getScuPerc().hashCode() );
         result = 37 * result + ( getScuDate() == null ? 0 : this.getScuDate().hashCode() );
         return result;
   }   


}


